# Generated by Django 5.2.10 on 2026-02-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Категория"
                    ),
                ),
                ("health_score", models.FloatField(verbose_name="Оценка")),
                (
                    "summary_note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Краткий вердикт"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="Фото"),
                ),
                ("analysis_data", models.JSONField(verbose_name="Полный JSON анализа")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
