# Generated by Django 5.2.10 on 2026-02-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_product_is_active_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
