# Generated by Django 5.2.10 on 2026-02-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[("google", "Google"), ("apple", "Apple")],
                max_length=20,
                null=True,
            ),
        ),
    ]
